import type React from "react";

/** Theme-aware inline styles for SOC pages (dark + light via CSS variables). */
export const ps: Record<string, React.CSSProperties> = {
  container: { display: "flex", flexDirection: "column", gap: 24 },
  header: { display: "flex", justifyContent: "space-between", alignItems: "flex-start", gap: 24, flexWrap: "wrap" },
  title: {
    fontFamily: "'Space Grotesk', 'Outfit', sans-serif",
    fontWeight: 800,
    fontSize: 32,
    color: "var(--brand-text-primary)",
    letterSpacing: -1,
    marginBottom: 8,
  },
  desc: { fontSize: 14, color: "var(--brand-text-secondary)", lineHeight: 1.6 },
  card: {
    background: "var(--glass-bg)",
    border: "1px solid var(--brand-border)",
    borderRadius: 12,
    padding: 16,
  },
  input: {
    width: "100%",
    padding: "10px 12px",
    background: "var(--brand-card)",
    border: "1px solid var(--brand-border)",
    borderRadius: 8,
    fontSize: 13,
    color: "var(--brand-text-primary)",
    outline: "none",
  },
  select: {
    padding: "10px 12px",
    background: "var(--brand-card)",
    border: "1px solid var(--brand-border)",
    borderRadius: 8,
    fontSize: 13,
    color: "var(--brand-text-primary)",
  },
  btnPrimary: {
    padding: "12px 20px",
    background: "var(--brand-cyan)",
    border: "none",
    borderRadius: 8,
    color: "#fff",
    fontWeight: 700,
    fontSize: 13,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  btnSecondary: {
    padding: "10px 16px",
    background: "var(--theme-white-bg-tint)",
    border: "1px solid var(--brand-border)",
    borderRadius: 8,
    color: "var(--brand-text-primary)",
    fontWeight: 600,
    fontSize: 12,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  badge: {
    display: "inline-block",
    padding: "4px 8px",
    borderRadius: 6,
    fontSize: 10,
    fontWeight: 700,
    textTransform: "uppercase",
  },
  label: {
    fontSize: 10,
    fontWeight: 600,
    color: "var(--brand-text-secondary)",
    textTransform: "uppercase",
    display: "block",
    marginBottom: 6,
  },
  modalOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 50,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  modalBackdrop: {
    position: "absolute",
    inset: 0,
    background: "rgba(0,0,0,0.55)",
    backdropFilter: "blur(10px)",
  },
  modal: {
    position: "relative",
    background: "var(--brand-card)",
    border: "1px solid var(--brand-border)",
    borderRadius: 12,
    padding: 20,
    maxWidth: 480,
    width: "100%",
    zIndex: 10,
  },
  table: {
    background: "var(--glass-bg)",
    border: "1px solid var(--brand-border)",
    borderRadius: 12,
    overflow: "hidden",
  },
  rowHover: { cursor: "pointer", transition: "background 0.15s" },
  mono: { fontFamily: "'JetBrains Mono', monospace" },
  muted: { color: "var(--brand-text-secondary)", fontSize: 12 },
  success: { color: "var(--brand-emerald)" },
  danger: { color: "var(--brand-crimson)" },
};

export const severityColors: Record<string, { bg: string; color: string; border: string }> = {
  critical: { bg: "rgba(196, 90, 106, 0.12)", color: "var(--brand-crimson)", border: "rgba(196, 90, 106, 0.25)" },
  high: { bg: "rgba(196, 154, 58, 0.12)", color: "var(--brand-amber)", border: "rgba(196, 154, 58, 0.25)" },
  medium: { bg: "rgba(99, 142, 203, 0.12)", color: "var(--brand-cyan)", border: "rgba(99, 142, 203, 0.25)" },
  low: { bg: "var(--theme-white-bg-tint)", color: "var(--brand-text-secondary)", border: "var(--brand-border)" },
};
